name: CD

# lắng nghe sự kiện
on:
   workflow_run:
      workflows: ["CI"]
      types:
         - completed

jobs:
   build:
      runs-on: node_50

      steps:
         - name: Xoá file .env cũ
           run: sudo rm -f .env

         - name: Tạo file .env mới
           run: |
              echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env
              echo "ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}}" >> .env
              echo "ACCESS_TOKEN_EXPIRES=${{secrets.ACCESS_TOKEN_EXPIRES}}" >> .env
              echo "REFRESH_TOKEN_SECRET=${{secrets.REFRESH_TOKEN_SECRET}}" >> .env
              echo "REFRESH_TOKEN_EXPIRES=${{secrets.REFRESH_TOKEN_EXPIRES}}" >> .env
              echo "GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}" >> .env
              echo "GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}" >> .env

         - name: Dừng và xoá container BE
           run: |
              sudo docker container stop con-cyber_community || true
              sudo docker container remove con-cyber_community || true

         - name: Xoá image cũ
           run: sudo docker image remove vulebaolong/img-cyber_community:latest || true

         - name: Chạy docker compose (nếu không có image thì sẽ kéo image từ docker hub)
           run: sudo docker compose up -d